site_name: marshsi
repo_url: https://github.com/UNEP-IMEO-MARS/marshsi
site_url: https://UNEP-IMEO-MARS.github.io/marshsi
site_description: 🛰️ Matched Filters retrievals for EMIT, PRISMA and EnMAP
site_author: Gonzalo Mateo-García
edit_uri: edit/main/docs/
repo_name: marshsi

nav:
  - Home: index.md
  - Tutorials:
    - Matched filters for EMIT: emit_example.ipynb
    - Matched filters for PRISMA: prisma_example.ipynb
    - Matched filters for EnMAP: enmap_example.ipynb

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
  - mknotebooks:
      execute: false
      timeout: 100
      allow_errors: false

theme:
  name: material
  language: en
  logo: logo.png
  favicon: logo.png
  highlightjs: true
  highlightjs_languages:
    - python
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UNEP-IMEO-MARS/marshsi

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
